import { empireDeclarations, frontierObjectives, getConflictEscalation, getConflictEscalationDecision, getConflictEscalationReady, getCourtCaseDecision, getCourtCaseReady, getDevelopmentScore, getEmpireDeclaration, getEmpireReady, getFirstEraComplete, getFrontierIntent, getFrontierObjectiveSecured, getImperialCourtCase, getNationDecision, getNationReady, getNextRetentionDecision, getOwnedPlot, getOwnedSectorIds, getPhase, getPopulation, getRivalPressure, getRivalResponse, getRivalResponseDecision, getRivalResponseReady, nationDecisions, nationSectorThreshold, type FrontierObjective, type PlayAction, type PlayState, type RetentionRecord } from "../lib/play-state";

function isCitySeed(state: PlayState) { const phase = getPhase(state); return phase === "city-seed" || phase === "nation-seed"; }

type InstitutionSeed = { label: string; district: string; workers: string; law: string };
type EmpireFoundingConsequence = { id: "order" | "expansion" | "prosperity"; label: string; short: string; effect: string; mandateId: "charter-courts" | "frontier-writs" | "basin-ledgers"; mandateLabel: string; mandateShort: string; mandateEffect: string };

function getEmpireFoundingConsequence(empireDeclaration: ReturnType<typeof getEmpireDeclaration>): EmpireFoundingConsequence | null {
  if (!empireDeclaration) return null;
  if (empireDeclaration.id === "frontier-crown") return { id: "expansion", label: "Expansion Mandate", short: "The empire is judged by the next frontier it can hold.", effect: "Future empire systems should prefer frontier claims, rival borders and outward pressure.", mandateId: "frontier-writs", mandateLabel: "Frontier Writs", mandateShort: "Written frontier rights turn conquest into a claim the council can enforce.", mandateEffect: "Future conflict systems can attach border pressure and rival response to this mandate." };
  if (empireDeclaration.id === "basin-hegemony") return { id: "prosperity", label: "Prosperity Pact", short: "The empire is judged by the wealth it can organize inside the basin.", effect: "Future empire systems should prefer trade, production and civic prosperity.", mandateId: "basin-ledgers", mandateLabel: "Basin Ledgers", mandateShort: "The first imperial ledgers make prosperity visible before deeper economy simulation.", mandateEffect: "Future economy systems can attach trade, tax and production upgrades to this mandate." };
  return { id: "order", label: "Imperial Order", short: "The empire is judged by the stability of its charter.", effect: "Future empire systems should prefer laws, institutions and legitimacy before war.", mandateId: "charter-courts", mandateLabel: "Charter Courts", mandateShort: "A standing charter court turns imperial order into a repeatable civic rule.", mandateEffect: "Future law systems can attach disputes, legitimacy and institution upgrades to this mandate." };
}

function getInstitutionSeeds(records: RetentionRecord[]): InstitutionSeed[] {
  return records.slice(0, 3).map((record) => {
    if (record.decisionId === "grain-levy") return record.choiceId === "authority" ? { label: "Granary Authority", district: "Granary District", workers: "levy stewards", law: "crown supply rights" } : { label: "Commons Stores", district: "Civic Commons", workers: "store keepers", law: "free household stores" };
    if (record.decisionId === "open-roads") return record.choiceId === "authority" ? { label: "Border Road Ward", district: "Guard Road", workers: "road wardens", law: "fortified passage" } : { label: "Open Market Road", district: "Market Street", workers: "caravan brokers", law: "open trade passage" };
    return record.choiceId === "authority" ? { label: "Scribe House", district: "Law Hall", workers: "civic scribes", law: "written council record" } : { label: "First Foundries", district: "Workshop Row", workers: "foundry crews", law: "chartered workshops" };
  });
}

const roadmap = [
  { label: "Land", detail: "claim one homeland", done: (state: PlayState) => state.ownedPlotIds.length > 0 },
  { label: "Settlement", detail: "raise shelter + storehouse", done: (state: PlayState) => state.settlementMarkers.includes("shelter") && state.settlementMarkers.includes("storehouse") },
  { label: "Village", detail: "market + council + watch", done: (state: PlayState) => state.settlementMarkers.includes("market") && state.settlementMarkers.includes("council") && state.settlementMarkers.includes("watch") },
  { label: "City", detail: "city seed: civic core, market route and defended streets", done: isCitySeed },
  { label: "Nation", detail: "hold 3 sectors, then choose a founding doctrine", done: (state: PlayState) => Boolean(state.nationDecisionId) },
  { label: "Era", detail: "resolve 3 post-founding seasons", done: (state: PlayState) => getFirstEraComplete(state) },
  { label: "Empire", detail: "secure a frontier objective, then declare the empire seed", done: (state: PlayState) => Boolean(state.empireDeclarationId) },
  { label: "Consequence", detail: "give the empire seed a system direction", done: (state: PlayState) => Boolean(getEmpireDeclaration(state)) },
  { label: "Mandate", detail: "record the first imperial law seed", done: (state: PlayState) => Boolean(getEmpireFoundingConsequence(getEmpireDeclaration(state))) },
  { label: "Court", detail: "resolve the first charter court case", done: (state: PlayState) => Boolean(state.courtCaseDecisionId) },
  { label: "Rival", detail: "answer the first rival rejection", done: (state: PlayState) => Boolean(state.rivalResponseDecisionId) },
  { label: "Escalation", detail: "choose war-prep, tariffs or envoys", done: (state: PlayState) => Boolean(state.conflictEscalationDecisionId) },
];

export function CouncilPanel({ state, dispatch }: { state: PlayState; dispatch: (action: PlayAction) => void }) {
  const phase = getPhase(state);
  const pressure = getRivalPressure(state);
  const population = getPopulation(state);
  const ownedSectors = getOwnedSectorIds(state);
  const nationReady = getNationReady(state);
  const nationDecision = getNationDecision(state);
  const frontierObjective = getFrontierIntent(state);
  const frontierObjectiveSecured = getFrontierObjectiveSecured(state);
  const empireReady = getEmpireReady(state);
  const empireDeclaration = getEmpireDeclaration(state);
  const empireConsequence = getEmpireFoundingConsequence(empireDeclaration);
  const courtCase = getImperialCourtCase(state);
  const courtDecision = getCourtCaseDecision(state);
  const courtCaseReady = getCourtCaseReady(state);
  const rivalResponse = getRivalResponse(state);
  const rivalResponseDecision = getRivalResponseDecision(state);
  const rivalResponseReady = getRivalResponseReady(state);
  const conflictEscalation = getConflictEscalation(state);
  const conflictEscalationDecision = getConflictEscalationDecision(state);
  const conflictEscalationReady = getConflictEscalationReady(state);
  const capital = getOwnedPlot(state)?.name ?? "Aurelian Basin";
  const completed = roadmap.filter((item) => item.done(state)).length;
  const firstEraComplete = getFirstEraComplete(state);
  const citySeed = isCitySeed(state);
  const rivalFrontierVisible = firstEraComplete && Boolean(nationDecision);

  return (
    <aside data-qa="council-panel" data-nation-decision={nationDecision?.id ?? "none"} data-retention-count={state.retentionRecords.length} data-era-complete={firstEraComplete ? "true" : "false"} data-city-institutions={firstEraComplete ? "true" : "false"} data-rival-frontier={rivalFrontierVisible ? "true" : "false"} data-frontier-intent={state.frontierIntentId ?? "none"} data-frontier-secured={frontierObjectiveSecured ? "true" : "false"} data-empire-ready={empireReady ? "true" : "false"} data-empire-declaration={state.empireDeclarationId ?? "none"} data-empire-consequence={empireConsequence?.id ?? "none"} data-imperial-mandate={empireConsequence?.mandateId ?? "none"} data-court-case-ready={courtCaseReady ? "true" : "false"} data-court-case-decision={state.courtCaseDecisionId ?? "none"} data-rival-response-ready={rivalResponseReady ? "true" : "false"} data-rival-response-decision={state.rivalResponseDecisionId ?? "none"} data-conflict-escalation-ready={conflictEscalationReady ? "true" : "false"} data-conflict-escalation-decision={state.conflictEscalationDecisionId ?? "none"} className="absolute bottom-[4.7rem] right-3 z-20 max-h-[calc(100%-10rem)] w-[min(560px,calc(100%-1.5rem))] overflow-auto rounded-3xl border border-amber-100/20 bg-black/66 p-3 shadow-2xl backdrop-blur-md md:bottom-[5.7rem] md:right-5 md:p-4">
      <p className="text-[9px] font-black uppercase tracking-[0.24em] text-amber-200/65">Council chamber</p>
      <div className="mt-1 flex items-start justify-between gap-3"><div><h2 className="text-2xl font-black text-amber-50 md:text-4xl">From land to empire</h2><p className="mt-1 text-xs leading-relaxed text-amber-50/65 md:text-sm">The demo now turns a court ruling into a rival conflict and first escalation choice.</p></div><span className="rounded-full border border-amber-200/25 bg-amber-200/10 px-3 py-1 text-[10px] font-black uppercase tracking-[0.16em] text-amber-100">{completed}/12</span></div>
      <div className="mt-4 grid grid-cols-4 gap-2 text-center"><Metric label="Phase" value={phase} /><Metric label="People" value={population} /><Metric label="Sectors" value={`${ownedSectors.length}/${nationSectorThreshold}`} /><Metric label="Rivals" value={`${pressure}%`} /></div>
      {citySeed ? <Panel qa="city-seed-milestone" tone="sky" eyebrow="City Seed" title="The village has a civic core, a market route and defended streets." body="This is not a full city yet, but it is no longer just a settlement." /> : null}
      {nationDecision ? <div data-qa="council-nation-founded" className="mt-4 rounded-2xl border border-emerald-200/40 bg-emerald-300/12 p-3"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-emerald-100/70">Nation founded</p><p className="mt-1 text-lg font-black text-amber-50">Aurelian Nation · {nationDecision.label}</p><p className="mt-1 text-xs leading-relaxed text-amber-50/62">Capital: {capital}. Controlled sectors: {ownedSectors.join(" · ")}. {nationDecision.effect}</p></div> : nationReady ? <ChoicePanel qa="council-nation-ready" eyebrow="Choose the founding doctrine" title="Three connected sectors now answer to your council." items={nationDecisions} itemQa="found-nation-choice" idAttr="data-decision-id" onPick={(id) => dispatch({ type: "foundNation", decisionId: id as never })} /> : <Panel eyebrow="Next strategic goal" title={`Claim ${Math.max(0, nationSectorThreshold - ownedSectors.length)} more connected sector${nationSectorThreshold - ownedSectors.length === 1 ? "" : "s"}`} />}
      {rivalFrontierVisible ? <RivalFrontierSeed pressure={pressure} ownedSectors={ownedSectors.length} selectedObjective={frontierObjective} objectiveSecured={frontierObjectiveSecured} dispatch={dispatch} /> : null}
      {empireReady ? <EmpireDeclarationSeed state={state} capital={capital} ownedSectors={ownedSectors} nationDecision={nationDecision} frontierObjective={frontierObjective} empireDeclaration={empireDeclaration} empireConsequence={empireConsequence} dispatch={dispatch} /> : null}
      {empireDeclaration ? <ImperialCourtCaseSeed courtCase={courtCase} courtDecision={courtDecision} dispatch={dispatch} /> : null}
      {rivalResponse ? <RivalResponseSeed response={rivalResponse} decision={rivalResponseDecision} dispatch={dispatch} /> : null}
      {conflictEscalation ? <ConflictEscalationSeed escalation={conflictEscalation} decision={conflictEscalationDecision} dispatch={dispatch} /> : null}
      {firstEraComplete ? <CityInstitutionsSeed records={state.retentionRecords} /> : null}
      {nationDecision && state.foundingCeremonySeen ? <SeasonLoop state={state} dispatch={dispatch} complete={firstEraComplete} /> : null}
      <div className="mt-4 space-y-2">{roadmap.map((item) => { const done = item.done(state); return <div key={item.label} data-qa={`roadmap-${item.label.toLowerCase()}`} className={`rounded-2xl border p-3 ${done ? "border-emerald-200/30 bg-emerald-300/10" : "border-amber-100/12 bg-white/5"}`}><div className="flex items-center justify-between gap-3"><p className="text-sm font-black text-amber-50">{item.label}</p><p className={`text-[10px] font-black uppercase tracking-[0.16em] ${done ? "text-emerald-100" : "text-amber-100/45"}`}>{done ? "done" : "next"}</p></div><p className="mt-1 text-xs leading-relaxed text-amber-50/62">{item.detail}</p></div>; })}</div>
      <Panel eyebrow="Latest chronicle" title={state.chronicle[0]?.title ?? "No chronicle yet"} body={state.chronicle[0]?.body ?? "Play actions will write the history here."} />
      <div className="mt-4 grid grid-cols-2 gap-2"><button data-qa="council-open-orders" onClick={() => dispatch({ type: "setView", view: "orders" })} className="rounded-2xl bg-amber-300 px-4 py-3 text-sm font-black text-stone-950 shadow-lg shadow-black/30 transition hover:bg-amber-200">Issue orders</button><button data-qa="council-open-world" onClick={() => dispatch({ type: "setView", view: "world" })} className="rounded-2xl border border-amber-100/18 bg-white/8 px-4 py-3 text-sm font-black text-amber-50 transition hover:bg-white/12">World map</button></div>
    </aside>
  );
}

function SeasonLoop({ state, dispatch, complete }: { state: PlayState; dispatch: (action: PlayAction) => void; complete: boolean }) {
  const decision = getNextRetentionDecision(state);
  if (complete) return <div data-qa="first-era-complete" className="mt-4 rounded-3xl border border-sky-200/35 bg-sky-300/12 p-3"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-sky-100/65">First Era Complete</p><p className="mt-1 text-lg font-black text-amber-50">The nation remembers its first three seasons.</p><div className="mt-3 space-y-2">{state.retentionRecords.map((record) => <RetentionRecordLine key={`${record.decisionId}-${record.choiceId}`} record={record} />)}</div></div>;
  if (!decision) return null;
  return <div data-qa="season-decision-panel" data-season-decision={decision.id} className="mt-4 overflow-hidden rounded-3xl border border-amber-200/35 bg-amber-300/12"><div className="border-b border-amber-100/14 bg-black/22 p-3"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-amber-100/65">Council decision · Season {decision.season}/3</p><p className="mt-1 text-lg font-black leading-tight text-amber-50">{decision.title}</p><p className="mt-2 text-xs leading-relaxed text-amber-50/68 md:text-sm">{decision.prompt}</p></div><div className="grid gap-2 p-3"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-amber-200/55">Choose one season order</p>{decision.choices.map((choice) => <button key={choice.id} type="button" data-qa="season-choice" data-decision-id={decision.id} data-choice-id={choice.id} onClick={() => dispatch({ type: "advanceSeason", decisionId: decision.id, choiceId: choice.id })} className="rounded-2xl border border-amber-100/20 bg-black/22 p-3 text-left transition hover:border-amber-200/45 hover:bg-amber-200/12"><span className="block text-sm font-black text-amber-50">{choice.label}</span><span className="mt-1 block text-xs leading-relaxed text-amber-50/58">{choice.short}</span></button>)}</div></div>;
}

function EmpireDeclarationSeed({ state, capital, ownedSectors, nationDecision, frontierObjective, empireDeclaration, empireConsequence, dispatch }: { state: PlayState; capital: string; ownedSectors: string[]; nationDecision: ReturnType<typeof getNationDecision>; frontierObjective: ReturnType<typeof getFrontierIntent>; empireDeclaration: ReturnType<typeof getEmpireDeclaration>; empireConsequence: EmpireFoundingConsequence | null; dispatch: (action: PlayAction) => void }) {
  if (empireDeclaration) return <div data-qa="empire-declaration-recorded" data-empire-declaration={empireDeclaration.id} data-empire-consequence={empireConsequence?.id ?? "none"} data-imperial-mandate={empireConsequence?.mandateId ?? "none"} className="mt-4 rounded-3xl border border-amber-200/45 bg-amber-300/16 p-3"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-amber-100/75">Empire Seed Declared</p><p className="mt-1 text-xl font-black text-amber-50">{empireDeclaration.title}</p><p className="mt-1 text-xs leading-relaxed text-amber-50/66">Founder record: {capital} → Aurelian Nation → {frontierObjective?.target ?? "frontier secured"} → {empireDeclaration.label}.</p><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Metric label="Sectors" value={ownedSectors.length} /><Metric label="Doctrine" value={nationDecision?.label ?? "Nation"} /><Metric label="Score" value={getDevelopmentScore(state)} /></div>{empireConsequence ? <div data-qa="empire-founding-consequence" data-empire-consequence={empireConsequence.id} className="mt-3 rounded-2xl border border-amber-100/24 bg-black/24 p-3"><p className="text-[9px] font-black uppercase tracking-[0.18em] text-amber-100/62">Founding consequence</p><p className="mt-1 text-sm font-black text-amber-50">{empireConsequence.label}</p><p className="mt-1 text-xs leading-relaxed text-amber-50/60">{empireConsequence.short}</p><div data-qa="imperial-mandate-seed" data-imperial-mandate={empireConsequence.mandateId} className="mt-3 rounded-2xl border border-amber-100/20 bg-amber-100/10 p-3"><p className="text-[9px] font-black uppercase tracking-[0.18em] text-amber-100/62">First imperial mandate</p><p className="mt-1 text-sm font-black text-amber-50">{empireConsequence.mandateLabel}</p><p className="mt-1 text-xs leading-relaxed text-amber-50/60">{empireConsequence.mandateShort}</p></div></div> : null}</div>;
  return <ChoicePanel qa="empire-declaration-options" eyebrow="Empire Declaration Seed" title="The secured frontier can become an empire claim." items={empireDeclarations.map((item) => ({ id: item.id, label: item.title, short: item.short, effect: item.effect }))} itemQa="empire-declaration-choice" idAttr="data-empire-declaration" onPick={(id) => dispatch({ type: "declareEmpire", declarationId: id as never })} />;
}

function ImperialCourtCaseSeed({ courtCase, courtDecision, dispatch }: { courtCase: ReturnType<typeof getImperialCourtCase>; courtDecision: ReturnType<typeof getCourtCaseDecision>; dispatch: (action: PlayAction) => void }) {
  if (!courtCase) return null;
  if (courtDecision) return <div data-qa="court-case-recorded" data-court-case={courtCase.id} data-court-case-decision={courtDecision.id} className="mt-4 rounded-3xl border border-emerald-200/35 bg-emerald-300/12 p-3"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-emerald-100/70">Court case resolved</p><p className="mt-1 text-lg font-black text-amber-50">{courtCase.title}</p><p className="mt-1 text-sm font-black text-emerald-100">{courtDecision.label}</p><p className="mt-1 text-xs leading-relaxed text-amber-50/62">{courtDecision.effect}</p></div>;
  return <ChoicePanel qa="court-case-options" extra={{ "data-court-case": courtCase.id }} eyebrow="Imperial Court Case v1" title={courtCase.title} body={courtCase.prompt} items={courtCase.decisions} itemQa="court-case-choice" idAttr="data-court-case-decision" onPick={(id) => dispatch({ type: "resolveCourtCase", decisionId: id as never })} />;
}

function RivalResponseSeed({ response, decision, dispatch }: { response: ReturnType<typeof getRivalResponse>; decision: ReturnType<typeof getRivalResponseDecision>; dispatch: (action: PlayAction) => void }) {
  if (!response) return null;
  if (decision) return <div data-qa="rival-response-recorded" data-rival-response={response.id} data-rival-response-decision={decision.id} className="mt-4 rounded-3xl border border-red-200/40 bg-red-500/12 p-3"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-red-100/70">Rival response answered</p><p className="mt-1 text-lg font-black text-amber-50">{response.title}</p><p className="mt-1 text-sm font-black text-red-100">{decision.label}</p><p className="mt-1 text-xs leading-relaxed text-amber-50/62">{decision.effect}</p></div>;
  return <ChoicePanel qa="rival-response-options" extra={{ "data-rival-response": response.id }} eyebrow="First Rival Response" title={`${response.rival} rejects the ruling`} body={response.prompt} items={response.decisions} itemQa="rival-response-choice" idAttr="data-rival-response-decision" onPick={(id) => dispatch({ type: "resolveRivalResponse", decisionId: id as never })} tone="red" />;
}

function ConflictEscalationSeed({ escalation, decision, dispatch }: { escalation: ReturnType<typeof getConflictEscalation>; decision: ReturnType<typeof getConflictEscalationDecision>; dispatch: (action: PlayAction) => void }) {
  if (!escalation) return null;
  if (decision) return <div data-qa="conflict-escalation-recorded" data-conflict-escalation={escalation.id} data-conflict-escalation-decision={decision.id} className="mt-4 rounded-3xl border border-orange-200/40 bg-orange-500/12 p-3"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-orange-100/70">Conflict escalation chosen</p><p className="mt-1 text-lg font-black text-amber-50">{escalation.title}</p><p className="mt-1 text-sm font-black text-orange-100">{decision.label}</p><p className="mt-1 text-xs leading-relaxed text-amber-50/62">{decision.effect}</p></div>;
  return <ChoicePanel qa="conflict-escalation-options" extra={{ "data-conflict-escalation": escalation.id }} eyebrow="Conflict Escalation Choice v1" title={escalation.title} body={escalation.prompt} items={escalation.decisions} itemQa="conflict-escalation-choice" idAttr="data-conflict-escalation-decision" onPick={(id) => dispatch({ type: "resolveConflictEscalation", decisionId: id as never })} tone="orange" />;
}

function CityInstitutionsSeed({ records }: { records: RetentionRecord[] }) { const institutions = getInstitutionSeeds(records); return <div data-qa="city-institutions-seed" className="mt-4 rounded-3xl border border-purple-200/35 bg-purple-300/12 p-3"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-purple-100/70">City Institutions Seed</p><p className="mt-1 text-lg font-black text-amber-50">Districts, workers and laws emerge from the first era.</p><div className="mt-3 grid gap-2">{institutions.map((institution) => <div key={institution.label} data-qa="city-institution-card" data-district={institution.district} className="rounded-2xl border border-purple-100/18 bg-black/24 p-3"><p className="text-sm font-black text-amber-50">{institution.label}</p><p className="mt-1 text-xs leading-relaxed text-amber-50/58">{institution.district} · {institution.workers}</p><p className="mt-2 text-[11px] leading-relaxed text-amber-50/55">Law: {institution.law}</p></div>)}</div></div>; }

function RivalFrontierSeed({ pressure, ownedSectors, selectedObjective, objectiveSecured, dispatch }: { pressure: number; ownedSectors: number; selectedObjective: FrontierObjective | null; objectiveSecured: boolean; dispatch: (action: PlayAction) => void }) { return <div data-qa="rival-frontier-seed" data-rival-pressure={pressure} data-frontier-secured={objectiveSecured ? "true" : "false"} className="mt-4 rounded-3xl border border-red-200/35 bg-red-500/12 p-3"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-red-100/70">Rival Frontier Seed</p><p className="mt-1 text-lg font-black text-amber-50">The frontier is no longer passive.</p><div className="mt-3 grid grid-cols-3 gap-2 text-center"><Metric label="Pressure" value={`${pressure}%`} /><Metric label="Sectors" value={ownedSectors} /><Metric label="Next" value={objectiveSecured ? "Secured" : selectedObjective ? "Chosen" : "Choose"} /></div>{selectedObjective ? <div data-qa="frontier-objective-recorded" data-frontier-intent={selectedObjective.id} className="mt-3 rounded-2xl border border-red-100/20 bg-black/26 p-3"><p className="text-[9px] font-black uppercase tracking-[0.18em] text-red-100/60">Expansion intent recorded</p><p className="mt-1 text-sm font-black text-amber-50">{selectedObjective.label}</p><p className="mt-1 text-xs leading-relaxed text-amber-50/58">{selectedObjective.target} · {objectiveSecured ? selectedObjective.secured : selectedObjective.result}</p></div> : <div data-qa="frontier-objective-options" className="mt-3 grid gap-2"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-red-100/60">Choose the next expansion objective</p>{frontierObjectives.map((objective) => <button key={objective.id} type="button" data-qa="frontier-objective-choice" data-frontier-intent={objective.id} onClick={() => dispatch({ type: "setFrontierIntent", intentId: objective.id })} className="rounded-2xl border border-red-100/20 bg-black/24 p-3 text-left transition hover:border-red-100/45 hover:bg-red-200/10"><span className="block text-sm font-black text-amber-50">{objective.label}</span><span className="mt-1 block text-xs leading-relaxed text-amber-50/58">{objective.target} · {objective.reason}</span></button>)}</div>}</div>; }

function ChoicePanel({ qa, extra, eyebrow, title, body, items, itemQa, idAttr, onPick, tone = "amber" }: { qa: string; extra?: Record<string, string>; eyebrow: string; title: string; body?: string; items: { id: string; label: string; short: string; effect?: string }[]; itemQa: string; idAttr: string; onPick: (id: string) => void; tone?: "amber" | "red" | "orange" }) { const border = tone === "red" ? "border-red-200/35 bg-red-500/12" : tone === "orange" ? "border-orange-200/40 bg-orange-500/12" : "border-amber-200/35 bg-amber-300/12"; return <div data-qa={qa} {...extra} className={`mt-4 rounded-3xl border p-3 ${border}`}><p className="text-[9px] font-black uppercase tracking-[0.2em] text-amber-100/70">{eyebrow}</p><p className="mt-1 text-lg font-black text-amber-50">{title}</p>{body ? <p className="mt-1 text-xs leading-relaxed text-amber-50/62">{body}</p> : null}<div className="mt-3 grid gap-2">{items.map((item) => <button key={item.id} type="button" data-qa={itemQa} {...{ [idAttr]: item.id }} onClick={() => onPick(item.id)} className="rounded-2xl border border-amber-100/20 bg-black/24 p-3 text-left transition hover:border-amber-100/50 hover:bg-amber-200/10"><span className="block text-sm font-black text-amber-50">{item.label}</span><span className="mt-1 block text-xs leading-relaxed text-amber-50/58">{item.short}</span>{item.effect ? <span className="mt-1 block text-[11px] font-bold text-amber-100/70">{item.effect}</span> : null}</button>)}</div></div>; }
function Panel({ qa, eyebrow, title, body, tone = "amber" }: { qa?: string; eyebrow: string; title: string; body?: string; tone?: "amber" | "sky" }) { const border = tone === "sky" ? "border-sky-200/35 bg-sky-300/12" : "border-amber-100/14 bg-amber-100/8"; return <div data-qa={qa} className={`mt-4 rounded-2xl border p-3 ${border}`}><p className="text-[9px] font-black uppercase tracking-[0.2em] text-amber-200/55">{eyebrow}</p><p className="mt-1 text-sm font-black text-amber-50">{title}</p>{body ? <p className="mt-1 text-xs leading-relaxed text-amber-50/62">{body}</p> : null}</div>; }
function RetentionRecordLine({ record }: { record: RetentionRecord }) { return <div data-qa="retention-record" data-decision-id={record.decisionId} data-choice-id={record.choiceId} data-village-marker={record.villageMarker} data-world-marker={record.worldMarker} className="rounded-2xl border border-sky-100/18 bg-black/22 p-3"><p className="text-[9px] font-black uppercase tracking-[0.16em] text-sky-100/55">Season {record.season}</p><p className="mt-1 text-sm font-black text-amber-50">{record.label}</p><p className="mt-2 text-[11px] leading-relaxed text-amber-50/55">Village: {record.villageMarker} · World: {record.worldMarker}</p></div>; }
function Metric({ label, value }: { label: string | number; value?: string | number }) { return <div className="rounded-2xl border border-amber-100/12 bg-black/28 px-2 py-2"><p className="text-[8px] font-black uppercase tracking-[0.16em] text-amber-200/50">{label}</p><p className="text-sm font-black text-amber-50 md:text-base">{value}</p></div>; }
